const express = require("express");
const router = express.Router();

const authRoutes = require("./auth.routes");
const userRoutes = require("./user.routes");
const rollRoutes = require("./roll.routes");
const chatRoutes = require("./chat.routes");
const postRoutes = require("./post.routes");
const achievementRoutes = require("./achievement.routes");
const newsRoutes = require("./news.routes");
const beltVerificationRoutes = require("./beltVerification.routes");
const beltEndorsementRoutes = require("./beltEndorsement.routes");
const trainingPartnersRoutes = require("./trainingPartners.routes");
const rollRequestsRoutes = require("./rollRequests.routes");
const placesRoutes = require("./places.routes");
const supportRoutes = require("./support.routes");
const trainingLogRoutes = require("./trainingLog.routes");
const beltProgressRoutes = require("./beltProgress.routes");
const customTechniquesRoutes = require("./customTechniques.routes");
const notificationRoutes = require("./notification.routes");
const pushNotificationRoutes = require("./pushNotification.routes");
const eventRoutes = require("./event.routes");
const friendsRoutes = require("./friends.routes");
const trainingReminderRoutes = require("./trainingReminder.routes");
const leaderboardRoutes = require("./leaderboard.routes");
const engagementRoutes = require("./engagement.routes");
const sparringRoutes = require("./sparring.routes");

// Mount routes
router.use("/", authRoutes);
router.use("/", userRoutes);
router.use("/", rollRoutes);
router.use("/", chatRoutes);
router.use("/", postRoutes);
router.use("/", achievementRoutes);
router.use("/", newsRoutes);
router.use("/", beltVerificationRoutes);
router.use("/", beltEndorsementRoutes);
router.use("/", trainingPartnersRoutes);
router.use("/", rollRequestsRoutes);
router.use("/", placesRoutes);
router.use("/", supportRoutes);
router.use("/", trainingLogRoutes);
router.use("/", beltProgressRoutes);
router.use("/", customTechniquesRoutes);
router.use("/", notificationRoutes);
router.use("/", pushNotificationRoutes);
router.use("/", eventRoutes);
router.use("/", friendsRoutes);
router.use("/", trainingReminderRoutes);
router.use("/", leaderboardRoutes);
router.use("/", engagementRoutes);
router.use("/", sparringRoutes);

module.exports = router;
